n_latent: [25, 50, 100, 200]
learning_rate: [5e-5,1e-4,5e-4,1e-3,5e-3]
weight_decay: [1e-4]
n_epochs: [25,50,75]
kl_warm_up: [0]
beta: [0.,0.5,1,10,50,100,200,500]
scheduler: ['warm_restarts','null']
t_max: [10]
eta_min: [1e-7,1e-6]
t_mult: [1.,1.2,1.5,2]
batch_size: [50,100]
n_workers: [4]
loss_reduction: ['sum']
topology_grid: [0,50,75,100,150,200]
