learning_rate_vae: [1e-5,5e-5,1e-4,5e-4,1e-3,5e-3]
learning_rate_mlp: [1e-5,5e-5,1e-4,5e-4,1e-3,5e-3]
n_epochs: [25,50,75]
t_max: [10]
eta_min: [1e-7,1e-6]
t_mult: [1.,1.2,1.5,2]
batch_size: [50,75,100]
dropout_p: [0.,0.1,0.2,0.3,0.5]
n_workers: [4]
loss_reduction: ['sum']
topology_grid: [0,50,75,100,150,200]
